name: Build and deploy Project Zoe server

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: volta-cli/action@v1
        with:
          node-version: '18.x'
          npm-version: '8.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --forceExit

      - name: Create .env file
        env:
          PORT: ${{ secrets.PROD_PORT }}
          DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          DB_HOST: ${{ secrets.PROD_DB_HOST }}
          DB_PORT: ${{ secrets.PROD_DB_PORT }}
          DB_DATABASE: ${{ secrets.PROD_DB_DATABASE }}
          MAPS_URL: ${{ secrets.PROD_MAPS_URL }}
          MAPS_KEY: ${{ secrets.PROD_MAPS_KEY }}
          APP_URL: ${{ secrets.PROD_APP_URL }}
          POSTMARK_SERVER_TOKEN: ${{ secrets.PROD_POSTMARK_SERVER_TOKEN }}
          POSTMARK_MESSAGE_STREAM: ${{ secrets.PROD_POSTMARK_MESSAGE_STREAM }}
          EMAIL_SENDER: ${{ secrets.PROD_EMAIL_SENDER }}
        run: |
          cat > .env << EOF
          PORT=$PORT
          DB_USERNAME=$DB_USERNAME
          DB_PASSWORD=$DB_PASSWORD
          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT
          DB_DATABASE=$DB_DATABASE
          DB_SYNCHRONIZE=false
          MAPS_URL=$MAPS_URL
          MAPS_KEY=$MAPS_KEY
          APP_URL=$APP_URL
          POSTMARK_SERVER_TOKEN=$POSTMARK_SERVER_TOKEN
          POSTMARK_MESSAGE_STREAM=$POSTMARK_MESSAGE_STREAM
          EMAIL_SENDER=$EMAIL_SENDER
          DATABASE_URL=postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_DATABASE?schema=public
          EOF

      - name: Build
        run: DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs

      - name: Configure SSH
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SERVER_SSH_KEY" > ~/.ssh/projectzoe.key
          chmod 600 ~/.ssh/projectzoe.key
          cat >> ~/.ssh/config << EOF
          Host projectzoe-prod
            HostName $SERVER_HOST
            User $SERVER_USERNAME
            IdentityFile ~/.ssh/projectzoe.key
            StrictHostKeyChecking no
          EOF

      - name: Deploy dist
        run: rsync -rtvO --delete ./dist/ projectzoe-prod:/opt/projectzoe/production/server/dist/

      - name: Deploy source
        run: rsync -rtvO --delete ./ projectzoe-prod:/opt/projectzoe/production/server/raw/

      - name: Deploy node_modules
        run: rsync -rtvO --delete ./node_modules/ projectzoe-prod:/opt/projectzoe/production/server/node_modules/

      - name: Deploy .env
        run: |
          rsync -rtvO ./.env projectzoe-prod:/opt/projectzoe/production/server/
          rsync -rtvO ./.env projectzoe-prod:/opt/projectzoe/production/server/dist/

      - name: Run database migrations
        run: ssh projectzoe-prod 'cd /opt/projectzoe/production/server/raw/ && npm run migration:run'

      - name: Restart app
        run: ssh projectzoe-prod 'cd /opt/projectzoe/production/server/dist/ && pm2 delete zoeServer 2>/dev/null || true && production=true pm2 start src/main.js --name zoeServer'
